version: '3.9'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'postgres_client_db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: client
      POSTGRES_DB: client_db
    networks:
      - default

  app-client:
    build:
      context: .
    container_name: 'app_client_container'
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/client_db
    networks:
      - default
    depends_on:
      - postgres

networks:
  default:
    driver: bridge
    name: client-api-network
